language: java
sudo: required
deploy:
  local_dir: target/site
  provider: pages
  skip_cleanup: true
  github_token: qJhDeGoLnfvnz1sK1X2z # Set in travis-ci.org dashboard
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
script:
- mvn clean install
- mvn site
- ls -a
